example.property: "I AM IN THE DEFAULT"
spring.jpa.database: "ORACLE"
spring.datasource.platform:  "ORACLE"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "oracle.jdbc.driver.OracleDriver"
spring.datasource.url: "jdbc:oracle:thin:@192.168.73.5:1521:orcl"
spring.datasource.username: "xframe"
spring.datasource.password: "xframe"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.ORACLEDialect"
redis.server: "redis"
redis.port: "6379"
signing.key: "wbjh20181102"